### ISSUE TITLE
Editing-Service: 1.1 Setup a new Python project on GitHub

### ISSUE THREAD

**Issue by Neuramare** [Neuramare/nm-genvista-editing-service#1]

**Comment by angelolamonaca** [comment]
@Geinge01 nelle tue PRs puoi linkare le issue scrivendo un commento come questo:

Resolves #1
oppure
Fixes #1

In questo caso 1 perche' e' l'id di questa issue

Puoi scoprire di piu sul link tra PRs e issues qui:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
